// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MaxDrattcev/metrics_alerting_service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockMetricsStorage is an autogenerated mock type for the MetricsStorage type
type MockMetricsStorage struct {
	mock.Mock
}

type MockMetricsStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsStorage) EXPECT() *MockMetricsStorage_Expecter {
	return &MockMetricsStorage_Expecter{mock: &_m.Mock}
}

// GetAllMetrics provides a mock function with given fields: ctx
func (_m *MockMetricsStorage) GetAllMetrics(ctx context.Context) ([]models.Metrics, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMetrics")
	}

	var r0 []models.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Metrics, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Metrics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetricsStorage_GetAllMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMetrics'
type MockMetricsStorage_GetAllMetrics_Call struct {
	*mock.Call
}

// GetAllMetrics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMetricsStorage_Expecter) GetAllMetrics(ctx interface{}) *MockMetricsStorage_GetAllMetrics_Call {
	return &MockMetricsStorage_GetAllMetrics_Call{Call: _e.mock.On("GetAllMetrics", ctx)}
}

func (_c *MockMetricsStorage_GetAllMetrics_Call) Run(run func(ctx context.Context)) *MockMetricsStorage_GetAllMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMetricsStorage_GetAllMetrics_Call) Return(_a0 []models.Metrics, _a1 error) *MockMetricsStorage_GetAllMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetricsStorage_GetAllMetrics_Call) RunAndReturn(run func(context.Context) ([]models.Metrics, error)) *MockMetricsStorage_GetAllMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetric provides a mock function with given fields: ctx, mType, mName
func (_m *MockMetricsStorage) GetMetric(ctx context.Context, mType string, mName string) (models.Metrics, error) {
	ret := _m.Called(ctx, mType, mName)

	if len(ret) == 0 {
		panic("no return value specified for GetMetric")
	}

	var r0 models.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (models.Metrics, error)); ok {
		return rf(ctx, mType, mName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) models.Metrics); ok {
		r0 = rf(ctx, mType, mName)
	} else {
		r0 = ret.Get(0).(models.Metrics)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, mType, mName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetricsStorage_GetMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetric'
type MockMetricsStorage_GetMetric_Call struct {
	*mock.Call
}

// GetMetric is a helper method to define mock.On call
//   - ctx context.Context
//   - mType string
//   - mName string
func (_e *MockMetricsStorage_Expecter) GetMetric(ctx interface{}, mType interface{}, mName interface{}) *MockMetricsStorage_GetMetric_Call {
	return &MockMetricsStorage_GetMetric_Call{Call: _e.mock.On("GetMetric", ctx, mType, mName)}
}

func (_c *MockMetricsStorage_GetMetric_Call) Run(run func(ctx context.Context, mType string, mName string)) *MockMetricsStorage_GetMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMetricsStorage_GetMetric_Call) Return(_a0 models.Metrics, _a1 error) *MockMetricsStorage_GetMetric_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetricsStorage_GetMetric_Call) RunAndReturn(run func(context.Context, string, string) (models.Metrics, error)) *MockMetricsStorage_GetMetric_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCounter provides a mock function with given fields: ctx, metric
func (_m *MockMetricsStorage) UpdateCounter(ctx context.Context, metric models.Metrics) error {
	ret := _m.Called(ctx, metric)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCounter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Metrics) error); ok {
		r0 = rf(ctx, metric)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsStorage_UpdateCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCounter'
type MockMetricsStorage_UpdateCounter_Call struct {
	*mock.Call
}

// UpdateCounter is a helper method to define mock.On call
//   - ctx context.Context
//   - metric models.Metrics
func (_e *MockMetricsStorage_Expecter) UpdateCounter(ctx interface{}, metric interface{}) *MockMetricsStorage_UpdateCounter_Call {
	return &MockMetricsStorage_UpdateCounter_Call{Call: _e.mock.On("UpdateCounter", ctx, metric)}
}

func (_c *MockMetricsStorage_UpdateCounter_Call) Run(run func(ctx context.Context, metric models.Metrics)) *MockMetricsStorage_UpdateCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Metrics))
	})
	return _c
}

func (_c *MockMetricsStorage_UpdateCounter_Call) Return(_a0 error) *MockMetricsStorage_UpdateCounter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsStorage_UpdateCounter_Call) RunAndReturn(run func(context.Context, models.Metrics) error) *MockMetricsStorage_UpdateCounter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGauge provides a mock function with given fields: ctx, metric
func (_m *MockMetricsStorage) UpdateGauge(ctx context.Context, metric models.Metrics) error {
	ret := _m.Called(ctx, metric)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGauge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Metrics) error); ok {
		r0 = rf(ctx, metric)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsStorage_UpdateGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGauge'
type MockMetricsStorage_UpdateGauge_Call struct {
	*mock.Call
}

// UpdateGauge is a helper method to define mock.On call
//   - ctx context.Context
//   - metric models.Metrics
func (_e *MockMetricsStorage_Expecter) UpdateGauge(ctx interface{}, metric interface{}) *MockMetricsStorage_UpdateGauge_Call {
	return &MockMetricsStorage_UpdateGauge_Call{Call: _e.mock.On("UpdateGauge", ctx, metric)}
}

func (_c *MockMetricsStorage_UpdateGauge_Call) Run(run func(ctx context.Context, metric models.Metrics)) *MockMetricsStorage_UpdateGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Metrics))
	})
	return _c
}

func (_c *MockMetricsStorage_UpdateGauge_Call) Return(_a0 error) *MockMetricsStorage_UpdateGauge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsStorage_UpdateGauge_Call) RunAndReturn(run func(context.Context, models.Metrics) error) *MockMetricsStorage_UpdateGauge_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMetrics provides a mock function with given fields: ctx, metrics
func (_m *MockMetricsStorage) UpdateMetrics(ctx context.Context, metrics []models.Metrics) error {
	ret := _m.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Metrics) error); ok {
		r0 = rf(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsStorage_UpdateMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetrics'
type MockMetricsStorage_UpdateMetrics_Call struct {
	*mock.Call
}

// UpdateMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics []models.Metrics
func (_e *MockMetricsStorage_Expecter) UpdateMetrics(ctx interface{}, metrics interface{}) *MockMetricsStorage_UpdateMetrics_Call {
	return &MockMetricsStorage_UpdateMetrics_Call{Call: _e.mock.On("UpdateMetrics", ctx, metrics)}
}

func (_c *MockMetricsStorage_UpdateMetrics_Call) Run(run func(ctx context.Context, metrics []models.Metrics)) *MockMetricsStorage_UpdateMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Metrics))
	})
	return _c
}

func (_c *MockMetricsStorage_UpdateMetrics_Call) Return(_a0 error) *MockMetricsStorage_UpdateMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsStorage_UpdateMetrics_Call) RunAndReturn(run func(context.Context, []models.Metrics) error) *MockMetricsStorage_UpdateMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsStorage creates a new instance of MockMetricsStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsStorage {
	mock := &MockMetricsStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
