// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/MaxDrattcev/metrics_alerting_service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockMetricsService is an autogenerated mock type for the MetricsService type
type MockMetricsService struct {
	mock.Mock
}

type MockMetricsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsService) EXPECT() *MockMetricsService_Expecter {
	return &MockMetricsService_Expecter{mock: &_m.Mock}
}

// GetAllMetrics provides a mock function with given fields: _a0
func (_m *MockMetricsService) GetAllMetrics(_a0 context.Context) ([]models.Metrics, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMetrics")
	}

	var r0 []models.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Metrics, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Metrics); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetricsService_GetAllMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMetrics'
type MockMetricsService_GetAllMetrics_Call struct {
	*mock.Call
}

// GetAllMetrics is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockMetricsService_Expecter) GetAllMetrics(_a0 interface{}) *MockMetricsService_GetAllMetrics_Call {
	return &MockMetricsService_GetAllMetrics_Call{Call: _e.mock.On("GetAllMetrics", _a0)}
}

func (_c *MockMetricsService_GetAllMetrics_Call) Run(run func(_a0 context.Context)) *MockMetricsService_GetAllMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMetricsService_GetAllMetrics_Call) Return(_a0 []models.Metrics, _a1 error) *MockMetricsService_GetAllMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetricsService_GetAllMetrics_Call) RunAndReturn(run func(context.Context) ([]models.Metrics, error)) *MockMetricsService_GetAllMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetric provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockMetricsService) GetMetric(_a0 context.Context, _a1 string, _a2 string) (string, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetMetric")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetricsService_GetMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetric'
type MockMetricsService_GetMetric_Call struct {
	*mock.Call
}

// GetMetric is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *MockMetricsService_Expecter) GetMetric(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockMetricsService_GetMetric_Call {
	return &MockMetricsService_GetMetric_Call{Call: _e.mock.On("GetMetric", _a0, _a1, _a2)}
}

func (_c *MockMetricsService_GetMetric_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *MockMetricsService_GetMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMetricsService_GetMetric_Call) Return(_a0 string, _a1 error) *MockMetricsService_GetMetric_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetricsService_GetMetric_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockMetricsService_GetMetric_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCounter provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockMetricsService) UpdateCounter(_a0 context.Context, _a1 string, _a2 string, _a3 *int64) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCounter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *int64) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsService_UpdateCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCounter'
type MockMetricsService_UpdateCounter_Call struct {
	*mock.Call
}

// UpdateCounter is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
//   - _a3 *int64
func (_e *MockMetricsService_Expecter) UpdateCounter(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockMetricsService_UpdateCounter_Call {
	return &MockMetricsService_UpdateCounter_Call{Call: _e.mock.On("UpdateCounter", _a0, _a1, _a2, _a3)}
}

func (_c *MockMetricsService_UpdateCounter_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string, _a3 *int64)) *MockMetricsService_UpdateCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*int64))
	})
	return _c
}

func (_c *MockMetricsService_UpdateCounter_Call) Return(_a0 error) *MockMetricsService_UpdateCounter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsService_UpdateCounter_Call) RunAndReturn(run func(context.Context, string, string, *int64) error) *MockMetricsService_UpdateCounter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGauge provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockMetricsService) UpdateGauge(_a0 context.Context, _a1 string, _a2 string, _a3 *float64) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGauge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *float64) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsService_UpdateGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGauge'
type MockMetricsService_UpdateGauge_Call struct {
	*mock.Call
}

// UpdateGauge is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
//   - _a3 *float64
func (_e *MockMetricsService_Expecter) UpdateGauge(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockMetricsService_UpdateGauge_Call {
	return &MockMetricsService_UpdateGauge_Call{Call: _e.mock.On("UpdateGauge", _a0, _a1, _a2, _a3)}
}

func (_c *MockMetricsService_UpdateGauge_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string, _a3 *float64)) *MockMetricsService_UpdateGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*float64))
	})
	return _c
}

func (_c *MockMetricsService_UpdateGauge_Call) Return(_a0 error) *MockMetricsService_UpdateGauge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsService_UpdateGauge_Call) RunAndReturn(run func(context.Context, string, string, *float64) error) *MockMetricsService_UpdateGauge_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMetrics provides a mock function with given fields: ctx, metrics
func (_m *MockMetricsService) UpdateMetrics(ctx context.Context, metrics []models.Metrics) error {
	ret := _m.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Metrics) error); ok {
		r0 = rf(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsService_UpdateMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetrics'
type MockMetricsService_UpdateMetrics_Call struct {
	*mock.Call
}

// UpdateMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics []models.Metrics
func (_e *MockMetricsService_Expecter) UpdateMetrics(ctx interface{}, metrics interface{}) *MockMetricsService_UpdateMetrics_Call {
	return &MockMetricsService_UpdateMetrics_Call{Call: _e.mock.On("UpdateMetrics", ctx, metrics)}
}

func (_c *MockMetricsService_UpdateMetrics_Call) Run(run func(ctx context.Context, metrics []models.Metrics)) *MockMetricsService_UpdateMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Metrics))
	})
	return _c
}

func (_c *MockMetricsService_UpdateMetrics_Call) Return(_a0 error) *MockMetricsService_UpdateMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsService_UpdateMetrics_Call) RunAndReturn(run func(context.Context, []models.Metrics) error) *MockMetricsService_UpdateMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsService creates a new instance of MockMetricsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsService {
	mock := &MockMetricsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
