// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockFileService is an autogenerated mock type for the FileService type
type MockFileService struct {
	mock.Mock
}

type MockFileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileService) EXPECT() *MockFileService_Expecter {
	return &MockFileService_Expecter{mock: &_m.Mock}
}

// LoadMeticsFromFile provides a mock function with given fields: ctx
func (_m *MockFileService) LoadMeticsFromFile(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadMeticsFromFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileService_LoadMeticsFromFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadMeticsFromFile'
type MockFileService_LoadMeticsFromFile_Call struct {
	*mock.Call
}

// LoadMeticsFromFile is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFileService_Expecter) LoadMeticsFromFile(ctx interface{}) *MockFileService_LoadMeticsFromFile_Call {
	return &MockFileService_LoadMeticsFromFile_Call{Call: _e.mock.On("LoadMeticsFromFile", ctx)}
}

func (_c *MockFileService_LoadMeticsFromFile_Call) Run(run func(ctx context.Context)) *MockFileService_LoadMeticsFromFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFileService_LoadMeticsFromFile_Call) Return(_a0 error) *MockFileService_LoadMeticsFromFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileService_LoadMeticsFromFile_Call) RunAndReturn(run func(context.Context) error) *MockFileService_LoadMeticsFromFile_Call {
	_c.Call.Return(run)
	return _c
}

// WriteMetricsFile provides a mock function with given fields: ctx
func (_m *MockFileService) WriteMetricsFile(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WriteMetricsFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileService_WriteMetricsFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMetricsFile'
type MockFileService_WriteMetricsFile_Call struct {
	*mock.Call
}

// WriteMetricsFile is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFileService_Expecter) WriteMetricsFile(ctx interface{}) *MockFileService_WriteMetricsFile_Call {
	return &MockFileService_WriteMetricsFile_Call{Call: _e.mock.On("WriteMetricsFile", ctx)}
}

func (_c *MockFileService_WriteMetricsFile_Call) Run(run func(ctx context.Context)) *MockFileService_WriteMetricsFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockFileService_WriteMetricsFile_Call) Return(_a0 error) *MockFileService_WriteMetricsFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileService_WriteMetricsFile_Call) RunAndReturn(run func(context.Context) error) *MockFileService_WriteMetricsFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileService creates a new instance of MockFileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileService {
	mock := &MockFileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
