// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// MockMetricsHandler is an autogenerated mock type for the MetricsHandler type
type MockMetricsHandler struct {
	mock.Mock
}

type MockMetricsHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsHandler) EXPECT() *MockMetricsHandler_Expecter {
	return &MockMetricsHandler_Expecter{mock: &_m.Mock}
}

// GetAllMetrics provides a mock function with given fields: c
func (_m *MockMetricsHandler) GetAllMetrics(c *gin.Context) {
	_m.Called(c)
}

// MockMetricsHandler_GetAllMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMetrics'
type MockMetricsHandler_GetAllMetrics_Call struct {
	*mock.Call
}

// GetAllMetrics is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockMetricsHandler_Expecter) GetAllMetrics(c interface{}) *MockMetricsHandler_GetAllMetrics_Call {
	return &MockMetricsHandler_GetAllMetrics_Call{Call: _e.mock.On("GetAllMetrics", c)}
}

func (_c *MockMetricsHandler_GetAllMetrics_Call) Run(run func(c *gin.Context)) *MockMetricsHandler_GetAllMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockMetricsHandler_GetAllMetrics_Call) Return() *MockMetricsHandler_GetAllMetrics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsHandler_GetAllMetrics_Call) RunAndReturn(run func(*gin.Context)) *MockMetricsHandler_GetAllMetrics_Call {
	_c.Run(run)
	return _c
}

// GetMetric provides a mock function with given fields: c
func (_m *MockMetricsHandler) GetMetric(c *gin.Context) {
	_m.Called(c)
}

// MockMetricsHandler_GetMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetric'
type MockMetricsHandler_GetMetric_Call struct {
	*mock.Call
}

// GetMetric is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockMetricsHandler_Expecter) GetMetric(c interface{}) *MockMetricsHandler_GetMetric_Call {
	return &MockMetricsHandler_GetMetric_Call{Call: _e.mock.On("GetMetric", c)}
}

func (_c *MockMetricsHandler_GetMetric_Call) Run(run func(c *gin.Context)) *MockMetricsHandler_GetMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockMetricsHandler_GetMetric_Call) Return() *MockMetricsHandler_GetMetric_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsHandler_GetMetric_Call) RunAndReturn(run func(*gin.Context)) *MockMetricsHandler_GetMetric_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function with given fields: c
func (_m *MockMetricsHandler) Update(c *gin.Context) {
	_m.Called(c)
}

// MockMetricsHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMetricsHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockMetricsHandler_Expecter) Update(c interface{}) *MockMetricsHandler_Update_Call {
	return &MockMetricsHandler_Update_Call{Call: _e.mock.On("Update", c)}
}

func (_c *MockMetricsHandler_Update_Call) Run(run func(c *gin.Context)) *MockMetricsHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockMetricsHandler_Update_Call) Return() *MockMetricsHandler_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsHandler_Update_Call) RunAndReturn(run func(*gin.Context)) *MockMetricsHandler_Update_Call {
	_c.Run(run)
	return _c
}

// UpdateMetrics provides a mock function with given fields: c
func (_m *MockMetricsHandler) UpdateMetrics(c *gin.Context) {
	_m.Called(c)
}

// MockMetricsHandler_UpdateMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetrics'
type MockMetricsHandler_UpdateMetrics_Call struct {
	*mock.Call
}

// UpdateMetrics is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockMetricsHandler_Expecter) UpdateMetrics(c interface{}) *MockMetricsHandler_UpdateMetrics_Call {
	return &MockMetricsHandler_UpdateMetrics_Call{Call: _e.mock.On("UpdateMetrics", c)}
}

func (_c *MockMetricsHandler_UpdateMetrics_Call) Run(run func(c *gin.Context)) *MockMetricsHandler_UpdateMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *MockMetricsHandler_UpdateMetrics_Call) Return() *MockMetricsHandler_UpdateMetrics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsHandler_UpdateMetrics_Call) RunAndReturn(run func(*gin.Context)) *MockMetricsHandler_UpdateMetrics_Call {
	_c.Run(run)
	return _c
}

// NewMockMetricsHandler creates a new instance of MockMetricsHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsHandler {
	mock := &MockMetricsHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
