// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "github.com/MaxDrattcev/metrics_alerting_service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockFileStorage is an autogenerated mock type for the FileStorage type
type MockFileStorage struct {
	mock.Mock
}

type MockFileStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileStorage) EXPECT() *MockFileStorage_Expecter {
	return &MockFileStorage_Expecter{mock: &_m.Mock}
}

// ReadMetrics provides a mock function with no fields
func (_m *MockFileStorage) ReadMetrics() ([]models.Metrics, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadMetrics")
	}

	var r0 []models.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Metrics, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Metrics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metrics)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileStorage_ReadMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadMetrics'
type MockFileStorage_ReadMetrics_Call struct {
	*mock.Call
}

// ReadMetrics is a helper method to define mock.On call
func (_e *MockFileStorage_Expecter) ReadMetrics() *MockFileStorage_ReadMetrics_Call {
	return &MockFileStorage_ReadMetrics_Call{Call: _e.mock.On("ReadMetrics")}
}

func (_c *MockFileStorage_ReadMetrics_Call) Run(run func()) *MockFileStorage_ReadMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileStorage_ReadMetrics_Call) Return(_a0 []models.Metrics, _a1 error) *MockFileStorage_ReadMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileStorage_ReadMetrics_Call) RunAndReturn(run func() ([]models.Metrics, error)) *MockFileStorage_ReadMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// WriteMetrics provides a mock function with given fields: metrics
func (_m *MockFileStorage) WriteMetrics(metrics []models.Metrics) error {
	ret := _m.Called(metrics)

	if len(ret) == 0 {
		panic("no return value specified for WriteMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]models.Metrics) error); ok {
		r0 = rf(metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileStorage_WriteMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMetrics'
type MockFileStorage_WriteMetrics_Call struct {
	*mock.Call
}

// WriteMetrics is a helper method to define mock.On call
//   - metrics []models.Metrics
func (_e *MockFileStorage_Expecter) WriteMetrics(metrics interface{}) *MockFileStorage_WriteMetrics_Call {
	return &MockFileStorage_WriteMetrics_Call{Call: _e.mock.On("WriteMetrics", metrics)}
}

func (_c *MockFileStorage_WriteMetrics_Call) Run(run func(metrics []models.Metrics)) *MockFileStorage_WriteMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]models.Metrics))
	})
	return _c
}

func (_c *MockFileStorage_WriteMetrics_Call) Return(_a0 error) *MockFileStorage_WriteMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileStorage_WriteMetrics_Call) RunAndReturn(run func([]models.Metrics) error) *MockFileStorage_WriteMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileStorage creates a new instance of MockFileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileStorage {
	mock := &MockFileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
