with-expecter: true
dir: "internal/mocks"
outpkg: "mocks"
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}.go"

packages:
  github.com/MaxDrattcev/metrics_alerting_service/internal/handler:
    interfaces:
      MetricsHandler: {}

  github.com/MaxDrattcev/metrics_alerting_service/internal/service:
    interfaces:
      MetricsService: {}
      FileService: {}

  github.com/MaxDrattcev/metrics_alerting_service/internal/repository:
    interfaces:
      MetricsStorage: {}
      FileStorage: {}