// Code generated by cmd/reset; DO NOT EDIT.
package models

func (resetableStruct *ResetableStruct) Reset() {
	if resetableStruct == nil {
		return
	}
	resetableStruct.i = 0
	resetableStruct.str = ""
	if resetableStruct.strP != nil {
		*resetableStruct.strP = ""
	}
	resetableStruct.s = resetableStruct.s[:0]
	clear(resetableStruct.m)
	if resetableStruct.child != nil {
		resetableStruct.child.Reset()
	}
}
