CREATE TABLE IF NOT EXISTS metrics (
    pk_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id VARCHAR(100) NOT NULL DEFAULT '',
    type VARCHAR(100) NOT NULL DEFAULT '',
    delta BIGINT,
    value DOUBLE PRECISION
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_metrics_id ON metrics(id);
