package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	marker      = "generate:reset"
	outputFile  = "reset.gen.go"
	generatedBy = "// Code generated by cmd/reset; DO NOT EDIT.\n"
)

func main() {
	root := flag.String("root", ".", "project root directory")
	flag.Parse()

	wd, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo,
		Dir:  wd,
	}

	loadPattern := "./..."
	if *root != "." && *root != "" {
		loadPattern = filepath.Clean(*root) + string(filepath.Separator) + "..."
	}
	pkgs, err := packages.Load(cfg, loadPattern)
	if err != nil {
		log.Fatal(err)
	}

	for _, pkg := range pkgs {
		if shouldSkipPackage(pkg) {
			continue
		}
		if len(pkg.Errors) > 0 {
			continue
		}

		structs := findMarkedStructs(pkg)
		if len(structs) == 0 {
			continue
		}

		dir := packageDir(pkg)
		if dir == "" {
			continue
		}

		content, err := generateFile(pkg.Name, structs, pkg.TypesInfo)
		if err != nil {
			log.Fatalf("generate %s: %v", pkg.PkgPath, err)
		}

		formatted, err := format.Source(content)
		if err != nil {
			log.Fatalf("format %s: %v", pkg.PkgPath, err)
		}

		outPath := filepath.Join(dir, outputFile)
		if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
			log.Fatalf("write %s: %v", outPath, err)
		}

		log.Printf("generated %s (%d struct(s))", outPath, len(structs))
	}
}

func shouldSkipPackage(pkg *packages.Package) bool {
	if pkg == nil || pkg.PkgPath == "" {
		return true
	}
	if strings.Contains(pkg.PkgPath, "/vendor/") {
		return true
	}
	if strings.HasSuffix(pkg.PkgPath, "/cmd/reset") {
		return true
	}
	if strings.Contains(pkg.PkgPath, "/testdata/") {
		return true
	}
	return false
}

func packageDir(pkg *packages.Package) string {
	if len(pkg.GoFiles) == 0 {
		return ""
	}
	return filepath.Dir(pkg.GoFiles[0])
}

type markedStruct struct {
	Name string
	Type *types.Struct
}

func findMarkedStructs(pkg *packages.Package) []markedStruct {
	var result []markedStruct
	seen := make(map[string]struct{})

	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}

			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok || st.Fields == nil {
					continue
				}
				if !hasMarker(gen.Doc) && !hasMarker(ts.Doc) {
					continue
				}

				obj := pkg.TypesInfo.Defs[ts.Name]
				named, ok := obj.Type().(*types.Named)
				if !ok {
					continue
				}
				strct, ok := named.Underlying().(*types.Struct)
				if !ok {
					continue
				}

				if _, exists := seen[ts.Name.Name]; exists {
					continue
				}
				seen[ts.Name.Name] = struct{}{}

				result = append(result, markedStruct{
					Name: ts.Name.Name,
					Type: strct,
				})
			}
		}
	}

	return result
}

func hasMarker(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if text == marker {
			return true
		}
	}
	return false
}

func generateFile(pkgName string, structs []markedStruct, info *types.Info) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString(generatedBy)
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	for i, s := range structs {
		if i > 0 {
			buf.WriteByte('\n')
		}
		writeResetMethod(&buf, s.Name, s.Type, info)
	}

	return buf.Bytes(), nil
}

func writeResetMethod(buf *bytes.Buffer, typeName string, strct *types.Struct, info *types.Info) {
	recv := receiverName(typeName)

	fmt.Fprintf(buf, "func (%s *%s) Reset() {\n", recv, typeName)
	fmt.Fprintf(buf, "\tif %s == nil {\n", recv)
	fmt.Fprintf(buf, "\t\treturn\n")
	fmt.Fprintf(buf, "\t}\n")

	for i := 0; i < strct.NumFields(); i++ {
		field := strct.Field(i)
		if !field.Exported() && !field.Anonymous() {
			// неэкспортируемые поля в том же пакете доступны
		}
		access := fmt.Sprintf("%s.%s", recv, fieldName(field))
		lines := resetStmts(field.Type(), access, info)
		for _, line := range lines {
			fmt.Fprintf(buf, "\t%s\n", line)
		}
	}

	buf.WriteString("}\n")
}

func fieldName(field *types.Var) string {
	if field.Anonymous() {
		t := field.Type()
		if named, ok := t.(*types.Named); ok {
			return named.Obj().Name()
		}
		if ptr, ok := t.(*types.Pointer); ok {
			if named, ok := ptr.Elem().(*types.Named); ok {
				return named.Obj().Name()
			}
		}
	}
	return field.Name()
}

func receiverName(typeName string) string {
	if typeName == "" {
		return "v"
	}
	return strings.ToLower(typeName[:1]) + typeName[1:]
}

func resetStmts(t types.Type, access string, info *types.Info) []string {
	switch u := t.Underlying().(type) {
	case *types.Basic:
		return []string{fmt.Sprintf("%s = %s", access, zeroLiteral(u))}

	case *types.Pointer:
		return resetPointer(u.Elem(), access)

	case *types.Slice:
		return []string{fmt.Sprintf("%s = %s[:0]", access, access)}

	case *types.Map:
		return []string{fmt.Sprintf("clear(%s)", access)}

	case *types.Array:
		return resetArray(u, access)

	case *types.Struct:
		return resetNested(t, access)

	case *types.Interface, *types.Chan, *types.Signature:
		return []string{fmt.Sprintf("%s = nil", access)}

	default:
		if hasResetMethod(t) {
			return resetNested(t, access)
		}
		return []string{fmt.Sprintf("%s = %s", access, zeroForNamed(t))}
	}
}

func resetPointer(elem types.Type, access string) []string {
	lines := []string{fmt.Sprintf("if %s != nil {", access)}

	switch e := elem.Underlying().(type) {
	case *types.Basic:
		lines = append(lines, fmt.Sprintf("\t*%s = %s", access, zeroLiteral(e)))

	case *types.Slice:
		lines = append(lines, fmt.Sprintf("\t*%s = (*%s)[:0]", access, access))

	case *types.Map:
		lines = append(lines, fmt.Sprintf("\tclear(*%s)", access))

	case *types.Struct:
		lines = append(lines, resetNestedStmts(types.NewPointer(elem), access, "\t")...)

	default:
		if _, ok := elem.Underlying().(*types.Struct); ok {
			lines = append(lines, resetNestedStmts(types.NewPointer(elem), access, "\t")...)
		} else if hasResetMethod(elem) {
			lines = append(lines, resetNestedStmts(types.NewPointer(elem), access, "\t")...)
		} else {
			lines = append(lines, fmt.Sprintf("\t*%s = %s", access, zeroForNamed(elem)))
		}
	}

	lines = append(lines, "}")
	return lines
}

func resetArray(arr *types.Array, access string) []string {
	elem := arr.Elem().Underlying().(*types.Basic)
	if elem == nil {
		return []string{fmt.Sprintf("for i := range %s { %s[i] = 0 }", access, access)}
	}
	return []string{
		fmt.Sprintf("for i := range %s {", access),
		fmt.Sprintf("\t%s[i] = %s", access, zeroLiteral(elem)),
		"}",
	}
}

func resetNested(t types.Type, access string) []string {
	return resetNestedStmts(t, access, "")
}

func resetNestedStmts(t types.Type, access, indent string) []string {
	if _, ok := t.Underlying().(*types.Interface); ok {
		return []string{
			fmt.Sprintf("%sif resetter, ok := (interface{})(%s).(interface{ Reset() }); ok {", indent, access),
			indent + "\tresetter.Reset()",
			indent + "}",
		}
	}
	if ptr, ok := t.(*types.Pointer); ok {
		if _, ok := ptr.Elem().Underlying().(*types.Struct); ok {
			return []string{indent + fmt.Sprintf("%s.Reset()", access)}
		}
	}
	if hasResetMethod(t) {
		if _, ok := t.(*types.Pointer); ok {
			return []string{indent + fmt.Sprintf("%s.Reset()", access)}
		}
		return []string{indent + fmt.Sprintf("(&%s).Reset()", access)}
	}
	return []string{
		fmt.Sprintf("%sif resetter, ok := (interface{})(%s).(interface{ Reset() }); ok {", indent, access),
		indent + "\tresetter.Reset()",
		indent + "}",
	}
}

func hasResetMethod(t types.Type) bool {
	switch tt := t.(type) {
	case *types.Named:
		return lookupReset(tt)
	case *types.Pointer:
		return lookupReset(tt.Elem())
	default:
		return false
	}
}

func lookupReset(t types.Type) bool {
	named, ok := t.(*types.Named)
	if !ok {
		return false
	}

	mset := types.NewMethodSet(types.NewPointer(named))
	return mset.Lookup(nil, "Reset") != nil
}

func zeroLiteral(b *types.Basic) string {
	switch b.Kind() {
	case types.Bool:
		return "false"
	case types.String:
		return `""`
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64, types.Uintptr,
		types.Float32, types.Float64, types.Complex64, types.Complex128:
		return "0"
	case types.UnsafePointer:
		return "nil"
	default:
		return "0"
	}
}

func zeroForNamed(t types.Type) string {
	switch tt := t.(type) {
	case *types.Named:
		return fmt.Sprintf("%s{}", tt.Obj().Name())
	case *types.Pointer:
		return fmt.Sprintf("(%s)(nil)", tt)
	default:
		return "0"
	}
}
